        m_ljetPtMin     = iConfig.getParameter<float>("ljetPtMin");
        m_ljetAbsEtaMax = iConfig.getParameter<float>("ljetAbsEtaMax");

        t_ljetPt   = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetPtLabel"));
        t_ljetEta  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetEtaLabel"));
        t_ljetPhi  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetPhiLabel"));
        t_ljetE    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetEnergyLabel"));
        t_ljetCSV  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetCSVLabel"));
        t_ljetCMVA = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetCMVALabel"));
        t_ljetCvsB = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetCvsBLabel"));
        t_ljetCvsL = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetCvsLLabel"));
        t_ljetJEC  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetJECLabel"));
        t_ljetY    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetYLabel"));
        t_ljetArea = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetAreaLabel"));
        t_ljetnHadEnergy = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetnHadEnergyLabel"));
        t_ljetnEMEnergy  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetnEMEnergyLabel"));
        t_ljetcHadEnergy = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetcHadEnergyLabel"));
        t_ljetcEMEnergy  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetcEMEnergyLabel"));
        t_ljetcMultip    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetcMultipLabel"));
        t_ljetnMultip    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetnMultipLabel"));
        t_ljetHadronFlavour = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetPartonFlavourLabel"));
        t_ljetPartonFlavour = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetHadronFlavourLabel"));
        t_ljettau1          = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljettau1Label"));
        t_ljettau2          = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljettau2Label"));
        t_ljettau3          = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljettau3Label"));
        t_ljetPrunedMass    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetPrunedMassLabel"));
        t_ljetTrimmedMass   = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetTrimmedMassLabel"));
        t_ljetFilteredMass  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetFilteredMassLabel"));
        t_ljetSoftDropMass  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetSoftDropMassLabel"));
        // AK8 Jets
        t_ljet_subjetIdx0   = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetIdx0Label"));
        t_ljet_subjetIdx1   = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetIdx1Label"));
        t_ljet_subjetHadFl  = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetHadronFlavourLabel"));
        t_ljet_subjetPt     = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetPtLabel"));
        t_ljet_subjetEta    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetEtaLabel"));
        t_ljet_subjetPhi    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetPhiLabel"));
        t_ljet_subjetEnergy = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetEnergyLabel"));
        t_ljet_subjetJEC    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetJECLabel"));
        t_ljet_subjetCSV    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetCSVLabel"));
        t_ljet_subjetCMVA   = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetCMVALabel"));

        if (m_useTruth){
            t_ljetGenPt     = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetGenPtLabel"));
            t_ljetGenEta    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetGenEtaLabel"));
            t_ljetGenPhi    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetGenPhiLabel"));
            t_ljetGenE      = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetGenELabel"));
            t_ljetGenCharge = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljetGenChargeLabel"));
            t_ljet_subjetGenPt     = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetGenPtLabel"));
            t_ljet_subjetGenEta    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetGenEtaLabel"));
            t_ljet_subjetGenPhi    = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetGenPhiLabel"));
            t_ljet_subjetGenE	   = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetGenELabel"));
            t_ljet_subjetGenCharge = consumes<std::vector<float>>(iConfig.getParameter<edm::InputTag>("ljet_subjetGenChargeLabel"));
        }
